// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhiIVGffnPdCsY3yhWQe1QMP0YNZs-d4M',
    appId: '1:1074747185101:web:940d720e86442624ca1684',
    messagingSenderId: '1074747185101',
    projectId: 'sheep-care',
    authDomain: 'sheep-care.firebaseapp.com',
    storageBucket: 'sheep-care.appspot.com',
    measurementId: 'G-WMPNP60NEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDimKz3dY5Qoq73pMMuGicnm8YplipBdP8',
    appId: '1:1074747185101:android:925f0ffd2c8736f3ca1684',
    messagingSenderId: '1074747185101',
    projectId: 'sheep-care',
    storageBucket: 'sheep-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvqQ3z36gpxfM29DuP-kKOLL7ccTSVYhw',
    appId: '1:1074747185101:ios:26c28875e1f79d00ca1684',
    messagingSenderId: '1074747185101',
    projectId: 'sheep-care',
    storageBucket: 'sheep-care.appspot.com',
    iosBundleId: 'com.example.sheepCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvqQ3z36gpxfM29DuP-kKOLL7ccTSVYhw',
    appId: '1:1074747185101:ios:26c28875e1f79d00ca1684',
    messagingSenderId: '1074747185101',
    projectId: 'sheep-care',
    storageBucket: 'sheep-care.appspot.com',
    iosBundleId: 'com.example.sheepCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhiIVGffnPdCsY3yhWQe1QMP0YNZs-d4M',
    appId: '1:1074747185101:web:49a25026ee0aae74ca1684',
    messagingSenderId: '1074747185101',
    projectId: 'sheep-care',
    authDomain: 'sheep-care.firebaseapp.com',
    storageBucket: 'sheep-care.appspot.com',
    measurementId: 'G-STZCKB4RCB',
  );
}
